# Use :nonroot base image for all containers
defaultBaseImage: gcr.io/distroless/static:nonroot
baseImageOverrides:
  knative.dev/serving/vendor/github.com/tsenart/vegeta: ubuntu:latest
  knative.dev/serving/cmd/queue: ubuntu:latest
